# Generated by Django 4.2.19 on 2025-02-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField()),
                ('zinguscoin', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('zingus', models.BooleanField(default=False)),
            ],
        ),
    ]
